"""empty message

Revision ID: 4c7323fe43be
Revises: 
Create Date: 2022-08-20 05:36:26.260718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c7323fe43be'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('library', sa.Column('name', sa.String(length=250), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('library', 'name')
    # ### end Alembic commands ###
