"""empty message

Revision ID: db68cd117777
Revises: 4c7323fe43be
Create Date: 2022-08-21 10:39:50.499078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db68cd117777'
down_revision = '4c7323fe43be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('books', 'book_status',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('books', 'book_status',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###
